security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        secured_area:
            pattern: ^/account
            anonymous: ~
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/account
            http_basic: ~
            provider: db_provider
#            guard:
#                authenticators:
#                    - AppBundle\Security\TokenAuthenticator


    access_control:
         - { path: '^/account', roles: ROLE_USER }
           
